package scrabble;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author student
 */
public class ScoreKeeper extends javax.swing.JFrame {

    /**
     * Creates new form ScrabbleScore
     */
    public ScoreKeeper() {
        selected = 1;
        initComponents();
        engine.initDictionary("ospd.txt");
        WordMatcher wordMatcher = new WordMatcher();
 //       wordMatcher.buildLetters("mesduaa");
   //     engine.findMatch(wordMatcher);
        wordMatcher.buildLetters("daofllt", "e");
        engine.findMatch(wordMatcher);
        engine.enterWord("amused", 7, 7, false);
        ScoreCalculator calculator = new ScoreCalculator();
        int score = engine.computeScore("fall", 7, 6, true, calculator);
        System.out.println(score);
        engine.enterWord("fall", 7, 6, true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        wordField1 = new javax.swing.JTextField();
        player1 = new javax.swing.JLabel();
        addButton1 = new javax.swing.JButton();
        scoreField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        singleWord = new javax.swing.JRadioButton();
        doubleWord = new javax.swing.JRadioButton();
        tripleWord = new javax.swing.JRadioButton();
        player2 = new javax.swing.JLabel();
        player3 = new javax.swing.JLabel();
        player4 = new javax.swing.JLabel();
        addButton2 = new javax.swing.JButton();
        addButton3 = new javax.swing.JButton();
        addButton4 = new javax.swing.JButton();
        scoreField2 = new javax.swing.JTextField();
        scoreField3 = new javax.swing.JTextField();
        scoreField4 = new javax.swing.JTextField();
        rowField = new javax.swing.JTextField();
        columnField = new javax.swing.JTextField();
        horizontalBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        wordField1.setToolTipText("");
        wordField1.setName("wordField1"); // NOI18N
        wordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wordField1ActionPerformed(evt);
            }
        });

        player1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        player1.setText("Player 1");

        addButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addButton1.setText("Add");
        addButton1.setName("addButton1"); // NOI18N
        addButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButton1ActionPerformed(evt);
            }
        });

        scoreField1.setEditable(false);
        scoreField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        scoreField1.setText("Score");
        scoreField1.setName("scoreField1"); // NOI18N
        scoreField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreField1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Enter your words to find the total score");

        buttonGroup1.add(singleWord);
        singleWord.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        singleWord.setSelected(true);
        singleWord.setText("Single Word");
        singleWord.setName(""); // NOI18N
        singleWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singleWordActionPerformed(evt);
            }
        });

        buttonGroup1.add(doubleWord);
        doubleWord.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        doubleWord.setText("Double Word");
        doubleWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doubleWordActionPerformed(evt);
            }
        });

        buttonGroup1.add(tripleWord);
        tripleWord.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tripleWord.setText("Triple Word");
        tripleWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tripleWordActionPerformed(evt);
            }
        });

        player2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        player2.setText("Player 3");

        player3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        player3.setText("Player 2");

        player4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        player4.setText("Player 4");

        addButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addButton2.setText("Add");
        addButton2.setName("addButton1"); // NOI18N
        addButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButton2ActionPerformed(evt);
            }
        });

        addButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addButton3.setText("Add");
        addButton3.setName("addButton1"); // NOI18N
        addButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButton3ActionPerformed(evt);
            }
        });

        addButton4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addButton4.setText("Add");
        addButton4.setName("addButton1"); // NOI18N
        addButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButton4ActionPerformed(evt);
            }
        });

        scoreField2.setEditable(false);
        scoreField2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        scoreField2.setText("Score");
        scoreField2.setName("scoreField1"); // NOI18N
        scoreField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreField2ActionPerformed(evt);
            }
        });

        scoreField3.setEditable(false);
        scoreField3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        scoreField3.setText("Score");
        scoreField3.setName("scoreField1"); // NOI18N
        scoreField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreField3ActionPerformed(evt);
            }
        });

        scoreField4.setEditable(false);
        scoreField4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        scoreField4.setText("Score");
        scoreField4.setName("scoreField1"); // NOI18N
        scoreField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreField4ActionPerformed(evt);
            }
        });

        rowField.setText("Row");
        rowField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rowFieldActionPerformed(evt);
            }
        });

        columnField.setText("Column");

        horizontalBox.setText("Horizontal");
        horizontalBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horizontalBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(player2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(player1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(player3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(player4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(wordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(columnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rowField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(horizontalBox)))))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addButton1)
                                .addGap(18, 18, 18)
                                .addComponent(scoreField1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tripleWord)
                            .addComponent(doubleWord)
                            .addComponent(singleWord)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addButton4)
                                .addGap(18, 18, 18)
                                .addComponent(scoreField4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addButton2)
                                .addGap(18, 18, 18)
                                .addComponent(scoreField2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addButton3)
                                .addGap(18, 18, 18)
                                .addComponent(scoreField3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(singleWord)
                    .addComponent(wordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(doubleWord)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tripleWord)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rowField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(horizontalBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(columnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton1)
                    .addComponent(scoreField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(player3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(player2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addButton2)
                            .addComponent(scoreField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addButton3)
                            .addComponent(scoreField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton4)
                    .addComponent(scoreField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void wordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wordField1ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_wordField1ActionPerformed
    private void addButtonActionPerformed(ScoreCalculator calculator, javax.swing.JTextField scoreField){
        String word = wordField1.getText().toLowerCase();
        wordField1.setText("");
        wordField1.requestFocus();
        //int score = calculator[0].calculate(word, selected);
        String row = rowField.getText();
        String column = columnField.getText();
        int rowInt = Integer.parseInt(row);
        int columnInt = Integer.parseInt(column);
        System.out.println("Row = "+row+", column = "+column+". Horizontal = "+bHorizontal+".");
        int score = engine.computeScore(word, rowInt, columnInt, bHorizontal, calculator);
        scoreField.setText(""+score);
    }
    private void addButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButton1ActionPerformed
        // TODO add your handling code here:
        addButtonActionPerformed(calculator[0], scoreField1);
    }//GEN-LAST:event_addButton1ActionPerformed

    private void scoreField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreField1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_scoreField1ActionPerformed

    private void singleWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singleWordActionPerformed
        // TODO add your handling code here:
        selected = 1;
    }//GEN-LAST:event_singleWordActionPerformed

    private void tripleWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tripleWordActionPerformed
        // TODO add your handling code here:
        selected = 3;
    }//GEN-LAST:event_tripleWordActionPerformed

    private void doubleWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doubleWordActionPerformed
        // TODO add your handling code here:
        selected = 2;
    }//GEN-LAST:event_doubleWordActionPerformed

    private void addButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButton2ActionPerformed
        // TODO add your handling code here:
        addButtonActionPerformed(calculator[1], scoreField2);
    }//GEN-LAST:event_addButton2ActionPerformed

    private void addButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButton3ActionPerformed
        // TODO add your handling code here:
        addButtonActionPerformed(calculator[2], scoreField3);
    }//GEN-LAST:event_addButton3ActionPerformed

    private void addButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButton4ActionPerformed
        // TODO add your handling code here:
        addButtonActionPerformed(calculator[3], scoreField4);
    }//GEN-LAST:event_addButton4ActionPerformed

    private void scoreField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scoreField2ActionPerformed

    private void scoreField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scoreField3ActionPerformed

    private void scoreField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scoreField4ActionPerformed

    private void rowFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rowFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rowFieldActionPerformed

    private void horizontalBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horizontalBoxActionPerformed
        // TODO add your handling code here:
        bHorizontal = !bHorizontal;
    }//GEN-LAST:event_horizontalBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScoreKeeper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScoreKeeper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScoreKeeper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScoreKeeper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScoreKeeper().setVisible(true);
            }
        });
    }
    ScrabbleEngine engine = new ScrabbleEngine();
    boolean bHorizontal = false;
    private int selected;
    private ScoreCalculator []calculator = new ScoreCalculator[4]; 
    
    {
        for (int i = 0; i<4; i++){
            calculator[i] = new ScoreCalculator();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton1;
    private javax.swing.JButton addButton2;
    private javax.swing.JButton addButton3;
    private javax.swing.JButton addButton4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField columnField;
    private javax.swing.JRadioButton doubleWord;
    private javax.swing.JCheckBox horizontalBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel player1;
    private javax.swing.JLabel player2;
    private javax.swing.JLabel player3;
    private javax.swing.JLabel player4;
    private javax.swing.JTextField rowField;
    private javax.swing.JTextField scoreField1;
    private javax.swing.JTextField scoreField2;
    private javax.swing.JTextField scoreField3;
    private javax.swing.JTextField scoreField4;
    private javax.swing.JRadioButton singleWord;
    private javax.swing.JRadioButton tripleWord;
    private javax.swing.JTextField wordField1;
    // End of variables declaration//GEN-END:variables
}
